//
//  SexBombPresenter.swift
//  CleanBandit
//
//  Created by ARDA TUPAL on 19/04/2017.
//  Copyright (c) 2017 ARDA TUPAL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SexBombPresenterOutput: class {
    func displaySomething(viewModel: SexBombViewModel)
}

class SexBombPresenter: SexBombInteractorOutput {
    weak var output: SexBombPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentSomething(response: SexBombResponse) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = SexBombViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
