//
//  SexBombWorker.swift
//  CleanBandit
//
//  Created by ARDA TUPAL on 19/04/2017.
//  Copyright (c) 2017 ARDA TUPAL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SexBombWorker {
  // MARK: Business Logic
  
  func doSomeWork() {
    // NOTE: Do the work
  }
}
